/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Shaikh
 */
public class ResultUpdateExtended extends javax.swing.JFrame {

    ResultUpdate obj = new ResultUpdate();
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public ResultUpdateExtended() {
        initComponents();
        STUDENT_NAME.setText(obj.student_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        STUDENT_NAME = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ictmid = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ictct = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ictfinal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        mathmid = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        mathct = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        mathfinal = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        sciencemid = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sciencect = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        sciencefinal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        socialsciencemid = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        socialsciencect = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        socialsciencefinal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        banglamid = new javax.swing.JTextField();
        banglact = new javax.swing.JTextField();
        banglafinal = new javax.swing.JTextField();
        englishmid = new javax.swing.JTextField();
        englishct = new javax.swing.JTextField();
        englishfinal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        gkmid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        gkct = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        gkfinal = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RESULT UPDATE ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 163, 46));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("STUDENT'S ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 51));

        STUDENT_NAME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        STUDENT_NAME.setText("jLabel3");
        jPanel1.add(STUDENT_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 266, 46));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("ICT(MID)");

        ictmid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("ICT(CT)");

        ictct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("ICT(FINAL)");

        ictfinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("MATH(MID)");

        mathmid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("MATH(CT)");

        mathct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("MATH(FINAL)");

        mathfinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("SCIENCE(MID)");

        sciencemid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("SCIENCE(CT)");

        sciencect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("SCIENCE(FINAL)");

        sciencefinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("SOCIAL SCIENCE(MID)");

        socialsciencemid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("SOCIAL SCIENCE(CT)");

        socialsciencect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        socialsciencect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialsciencectActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("SOCIAL SCIENCE(FINAL)");

        socialsciencefinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        socialsciencefinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialsciencefinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(sciencemid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sciencefinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(socialsciencemid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(socialsciencect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(socialsciencefinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mathfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mathct, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mathmid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ictfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ictct, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ictmid, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sciencect, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ictmid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ictct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ictfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(mathmid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(mathct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(mathfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(sciencemid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(sciencect, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(sciencefinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(socialsciencemid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(socialsciencect, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(socialsciencefinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 490, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("BANGLA(MID)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 264, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("BANGLA(CT)");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 314, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("BANGLA(FINAL)");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 364, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ENGLISH(CT)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 464, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ENGLISH(MID)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 414, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ENGLISH(FINAL)");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 514, -1, -1));

        banglamid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        banglamid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banglamidActionPerformed(evt);
            }
        });
        jPanel1.add(banglamid, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 257, 101, 32));

        banglact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        banglact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banglactActionPerformed(evt);
            }
        });
        jPanel1.add(banglact, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 307, 101, 32));

        banglafinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(banglafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 357, 101, 32));

        englishmid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(englishmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 407, 101, 32));

        englishct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(englishct, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 457, 101, 32));

        englishfinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(englishfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 507, 101, 32));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("GK(MID)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 559, -1, -1));

        gkmid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(gkmid, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 552, 101, 32));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("GK(CT)");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 609, -1, -1));

        gkct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(gkct, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 602, 101, 32));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("GK(FINAL)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 659, -1, -1));

        gkfinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(gkfinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 652, 101, 32));

        update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 220, 40));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/exit_48px.png"))); // NOI18N
        jLabel59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel59MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/back.png"))); // NOI18N
        jLabel58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel58MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/icon/back.png"))); // NOI18N
        jLabel60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel60MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1050, 747));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void socialsciencefinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialsciencefinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialsciencefinalActionPerformed

    private void socialsciencectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialsciencectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_socialsciencectActionPerformed

    private void jLabel59MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel59MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel59MouseClicked

    private void jLabel58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel58MouseClicked
        StudentPage obj = new StudentPage();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel58MouseClicked

    private void jLabel60MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel60MouseClicked
        ResultUpdate obj = new ResultUpdate();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel60MouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        conn= SqlConnection.ConnectDB();
        String waiver="0";
        String add1 = "0";
       String sql= "UPDATE student_result SET banglamid=?, banglact=?, banglafinal=?,englishmid=? ,englishct=?,englishfinal=?,gkmid=?, gkct=?, gkfinal=?, ictmid=?, ictct=?, ictfinal=?, mathmid=?, mathct=?, mathfinal=?, sciencemid=?, sciencect=?, sciencefinal=?,socialsciencemid=?, socialsciencect=?, socialsciencefinal=? WHERE studentid = ?";
       
       try
       {
              pst= conn.prepareStatement(sql);
          
    
               
               pst.setString(1,banglamid.getText());
               pst.setString(2,banglact.getText());
               pst.setString(3,banglafinal.getText());
               pst.setString(4,englishmid.getText());
               pst.setString(5,englishct.getText());
               pst.setString(6,englishfinal.getText());
               pst.setString(7,gkmid.getText());
               pst.setString(8,gkct.getText());
               pst.setString(9,gkfinal.getText());
               pst.setString(10,ictmid.getText());
               pst.setString(11,ictct.getText());
               pst.setString(12,ictfinal.getText());
               pst.setString(13,mathmid.getText());
               pst.setString(14,mathct.getText());
               pst.setString(15,mathfinal.getText());
               pst.setString(16,sciencemid.getText());
               pst.setString(17,sciencect.getText());
               pst.setString(18,sciencefinal.getText());
               pst.setString(19,socialsciencemid.getText());
               pst.setString(20,socialsciencect.getText());
               pst.setString(21,socialsciencefinal.getText());
              
               pst.setString(22,obj.student_id);
               
               pst.executeUpdate();
               
               double bangla_total,english_total,gk_total,ict_total,math_total,science_total,social_total; 
               
               double bang1 = Double.parseDouble(banglamid.getText());
               double bang2 = Double.parseDouble(banglact.getText());
               double bang3 = Double.parseDouble(banglafinal.getText());
               double eng1 = Double.parseDouble(englishmid.getText());
               double eng2 = Double.parseDouble(englishct.getText());
               double eng3 = Double.parseDouble(englishfinal.getText());
               double gk1 = Double.parseDouble(gkmid.getText());
               double gk2 = Double.parseDouble(gkct.getText());
               double gk3 = Double.parseDouble(gkfinal.getText());
               double ict1 = Double.parseDouble(ictmid.getText());
               double ict2 = Double.parseDouble(ictct.getText());
               double ict3 = Double.parseDouble(ictfinal.getText());
               double math1 = Double.parseDouble(mathmid.getText());
               double math2 = Double.parseDouble(mathct.getText());
               double math3 = Double.parseDouble(mathfinal.getText());
               double sci1 = Double.parseDouble(sciencemid.getText());
               double sci2 = Double.parseDouble(sciencect.getText());
               double sci3 = Double.parseDouble(sciencefinal.getText());
               double s_sci1 = Double.parseDouble(socialsciencemid.getText());
               double s_sci2 = Double.parseDouble(socialsciencect.getText());
               double s_sci3 = Double.parseDouble(socialsciencefinal.getText());
               
               bangla_total = bang1+bang2+bang3;
               english_total = eng1+eng2+eng3;
               gk_total = gk1+gk2+gk3;
               ict_total = ict1+ict2+ict3;
               math_total = math1+math2+math3;
               science_total = sci1+sci2+sci3;
               social_total = s_sci1+s_sci2+s_sci3;
               
               String banglaGrade,englishGrade,gkGrade,ictGrade,mathGrade,scienceGrade,socialGrade,banglaGPA,englishGPA,gkGPA,ictGPA,mathGPA,scienceGPA,socialGPA;
               
               if(bangla_total >= 80){
                   banglaGrade = "A+";
                   banglaGPA = "5.00";
               }
               else if(bangla_total >= 70 && bangla_total < 80){
                   banglaGrade = "A";
                   banglaGPA = "4.00";
               }
                else if(bangla_total >= 60 && bangla_total < 70){
                   banglaGrade = "B";
                   banglaGPA = "3.00";
               }
                else if(bangla_total >= 50 && bangla_total < 60){
                    banglaGrade = "C";
                   banglaGPA = "2.00";
               }
                else{
                    banglaGrade = "F";
                    banglaGPA = "0.00"; 
                }
               
               
               if(english_total >= 80){
                    englishGrade = "A+";
                   englishGPA = "5.00";
               }
               else if(english_total >= 70 && english_total < 80){
                   englishGrade = "A";
                    englishGPA = "4.00";
               }
                else if(english_total >= 60 && english_total < 70){
                   englishGrade = "B";
                   englishGPA = "3.00";
               }
                else if(english_total >= 50 && english_total < 60){
                    englishGrade = "C";
                   englishGPA = "2.00";
               }
                else{
                    englishGrade = "F";
                    englishGPA = "0.00"; 
                }
               
               if(gk_total >= 80){
                    gkGrade = "A+";
                    gkGPA = "5.00";
               }
               else if(gk_total >= 70 && gk_total < 80){
                   gkGrade = "A";
                   gkGPA = "4.00";
               }
                else if(gk_total >= 60 && gk_total < 70){
                  gkGrade = "B";
                  gkGPA = "3.00";
               }
                else if(gk_total >= 50 && gk_total < 60){
                   gkGrade = "C";
                   gkGPA = "2.00";
               }
                else{
                    gkGrade = "F";
                   gkGPA = "0.00"; 
                }
              
               
               if(ict_total >= 80){
                    ictGrade = "A+";
                    ictGPA = "5.00";
               }
               else if(ict_total >= 70 && ict_total < 80){
                   ictGrade = "A";
                   ictGPA = "4.00";
               }
                else if(ict_total >= 60 && ict_total < 70){
                   ictGrade = "B";
                   ictGPA = "3.00";
               }
                else if(ict_total >= 50 && ict_total < 60){
                  ictGrade = "C";
                   ictGPA = "2.00";
               }
                else{
                   ictGrade = "F";
                    ictGPA = "0.00"; 
                }
              
               
                if(math_total >= 80){
                    mathGrade = "A+";
                    mathGPA = "5.00";
               }
               else if(math_total >= 70 && math_total < 80){
                    mathGrade = "A";
                    mathGPA = "4.00";
               }
                else if(math_total >= 60 && math_total < 70){
                    mathGrade = "B";
                    mathGPA = "3.00";
               }
                else if(math_total >= 50 && math_total < 60){
                    mathGrade = "C";
                    mathGPA = "2.00";
               }
                else{
                    mathGrade = "F";
                    mathGPA = "0.00"; 
                }
                
                 if(science_total >= 80){
                    scienceGrade = "A+";
                    scienceGPA = "5.00";
               }
               else if(science_total >= 70 && science_total < 80){
                    scienceGrade = "A";
                    scienceGPA = "4.00";
               }
                else if(science_total >= 60 && science_total < 70){
                    scienceGrade = "B";
                    scienceGPA = "3.00";
               }
                else if(science_total >= 50 && science_total < 60){
                    scienceGrade = "C";
                    scienceGPA = "2.00";
               }
                else{
                    scienceGrade = "F";
                    scienceGPA = "0.00"; 
                }
                 
                 
                 if(social_total >= 80){
                    socialGrade = "A+";
                    socialGPA = "5.00";
               }
               else if(social_total >= 70 && social_total < 80){
                    socialGrade = "A";
                    socialGPA = "4.00";
               }
                else if(social_total >= 60 && social_total < 70){
                    socialGrade = "B";
                    socialGPA = "3.00";
               }
                else if(social_total >= 50 && social_total < 60){
                    socialGrade = "C";
                    socialGPA = "2.00";
               }
                else{
                    socialGrade = "F";
                    socialGPA = "0.00"; 
                }
                 
                //CACLCULATING TOTAL GPA
                double bangla_gpa = Double.parseDouble(banglaGPA);
                double english_gpa = Double.parseDouble(englishGPA);
                double gk_gpa = Double.parseDouble(gkGPA);
                double ict_gpa = Double.parseDouble(ictGPA);
                double math_gpa = Double.parseDouble(mathGPA);
                double science_gpa = Double.parseDouble(scienceGPA);
                double social_gpa = Double.parseDouble(socialGPA);
                
                double total_GPA;
                
                if(bangla_gpa!=0 || english_gpa!=0 || gk_gpa!=0 || ict_gpa!=0 || math_gpa!=0 || science_gpa!=0 || social_gpa!=0){
                    total_GPA = (bangla_gpa+english_gpa+gk_gpa+ict_gpa+math_gpa+science_gpa+social_gpa)/7.0;
                }
                else
                    total_GPA = 0;
                
                total_GPA = Math.round(total_GPA*100.0)/100.0;
                
                
                
                if(total_GPA == 5.00)
                    waiver = "50";
                else if(total_GPA >= 4.50)
                    waiver = "30";
                else if(total_GPA < 4.50 && total_GPA >=4.00)
                    waiver = "20";
                else
                    waiver = "0";
                
                //grade and gpa input in database
                
                 conn= SqlConnection.ConnectDB();
   
                 String sql1= "UPDATE student_result SET banglagpa=?,englishgpa=?,gkgpa=?,ictgpa=?,mathgpa=?,sciencegpa=?,socialsciencegpa=?,banglagrade=?,englishgrade=?,gkgrade=?,ictgrade=?,mathgrade=?,sciencegrade=?,socialsciencegrade=? WHERE studentid = ?";
       
               pst= conn.prepareStatement(sql1);
          
              
               pst.setString(1,banglaGPA);
               pst.setString(2,englishGPA);
               pst.setString(3,gkGPA);
               pst.setString(4,ictGPA);
               pst.setString(5,mathGPA);
               pst.setString(6,scienceGPA);
               pst.setString(7,socialGPA);
               pst.setString(8,banglaGrade);
               pst.setString(9,englishGrade);
               pst.setString(10,gkGrade);
               pst.setString(11,ictGrade);
               pst.setString(12,mathGrade);
               pst.setString(13,scienceGrade);
               pst.setString(14,socialGrade);
                             
               pst.setString(15,obj.student_id);
               
               pst.executeUpdate();
       
               //updating waiver,total gpa to database
              
               sql1 = "UPDATE accounts SET total_gpa=?,waiver=? WHERE studentid=?";     
               pst= conn.prepareStatement(sql1);
          
               String GPA_total = total_GPA+""; 
               pst.setString(1,GPA_total);
               pst.setString(2,waiver);
               pst.setString(3,obj.student_id);
               
               pst.executeUpdate();
               
       JOptionPane.showMessageDialog(null, "PROFILE UPDATED SUCCESFULLY !!!");    
    }catch (Exception e)
   {
       JOptionPane.showMessageDialog(null, e);       
   }
       double due=0;
       double waiverMoney=0;

       try{
           sql = "select tobe_paid,money_given from accounts where studentid=?";
           pst = conn.prepareStatement(sql);
           pst.setString(1,obj.student_id);
           rs= pst.executeQuery();
           String add = "0";
           if(rs.next()){
               add= rs.getString("tobe_paid");
               add1 = rs.getString("money_given");
           }
           double tobe_paid = Double.parseDouble(add);
           double waiver1 = Double.parseDouble(waiver);
           waiverMoney = (double)(waiver1*tobe_paid)/100.0;
                
           double v1 = Double.parseDouble(add);
           double v2 = Double.parseDouble(add1);
           due = v1-v2-waiverMoney; 
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null,e);     
       }
        conn = SqlConnection.ConnectDB();
        sql= "UPDATE accounts SET waiver_money = ?,due=? WHERE studentid = ?";
        try
       {  
           pst= conn.prepareStatement(sql);
           pst.setString(1,waiverMoney+"");
           pst.setString(2,due+"");
           pst.setString(3,obj.student_id);
           pst.executeUpdate();
       }                                       
       catch (Exception e)
       {
       JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_updateActionPerformed

    private void banglamidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banglamidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banglamidActionPerformed

    private void banglactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banglactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banglactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultUpdateExtended.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultUpdateExtended.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultUpdateExtended.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultUpdateExtended.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultUpdateExtended().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel STUDENT_NAME;
    private javax.swing.JTextField banglact;
    private javax.swing.JTextField banglafinal;
    private javax.swing.JTextField banglamid;
    private javax.swing.JTextField englishct;
    private javax.swing.JTextField englishfinal;
    private javax.swing.JTextField englishmid;
    private javax.swing.JTextField gkct;
    private javax.swing.JTextField gkfinal;
    private javax.swing.JTextField gkmid;
    private javax.swing.JTextField ictct;
    private javax.swing.JTextField ictfinal;
    private javax.swing.JTextField ictmid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField mathct;
    private javax.swing.JTextField mathfinal;
    private javax.swing.JTextField mathmid;
    private javax.swing.JTextField sciencect;
    private javax.swing.JTextField sciencefinal;
    private javax.swing.JTextField sciencemid;
    private javax.swing.JTextField socialsciencect;
    private javax.swing.JTextField socialsciencefinal;
    private javax.swing.JTextField socialsciencemid;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
